-- =============================================
-- MADVENTURE - COMPLETE CONSOLIDATED MIGRATIONS
-- Compiled at: 2026-07-16T14:34:23Z
-- Compiled via PowerShell
-- Do not edit this file directly. Edit the migration scripts under supabase/migrations/ instead.
-- =============================================

-- =============================================
-- FILE: 01_schema.sql
-- =============================================

-- Migration 01: Core Entities Schema

-- Note: Ensure uuid-ossp extension is enabled in Supabase if gen_random_uuid() is missing in very old versions, 
-- but it is usually available by default in modern Postgres.

CREATE TABLE districts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    division TEXT NOT NULL,
    description TEXT,
    climate TEXT,
    best_time_to_visit TEXT,
    rating NUMERIC DEFAULT 0.0,
    cover_image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE tours (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    district_id TEXT REFERENCES districts(id) ON DELETE CASCADE,
    duration TEXT,
    group_size_min INTEGER,
    group_size_max INTEGER,
    price_per_person NUMERIC NOT NULL,
    difficulty TEXT,
    featured_image TEXT,
    rating NUMERIC DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE hotels (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    district_id TEXT REFERENCES districts(id) ON DELETE CASCADE,
    type TEXT,
    price_per_night NUMERIC NOT NULL,
    rating NUMERIC DEFAULT 0.0,
    amenities TEXT[],
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE restaurants (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    district_id TEXT REFERENCES districts(id) ON DELETE CASCADE,
    cuisine_type TEXT,
    price_range TEXT,
    rating NUMERIC DEFAULT 0.0,
    is_halal BOOLEAN DEFAULT TRUE,
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL, -- usually UUID mapping to auth.users
    entity_id TEXT NOT NULL,
    entity_type TEXT NOT NULL, -- 'tour' or 'hotel'
    booking_date DATE NOT NULL,
    total_price NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    photos TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Row Level Security (RLS) Boilerplate Examples
ALTER TABLE tours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tours are visible to everyone" ON tours FOR SELECT USING (true);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own bookings" ON bookings FOR SELECT USING (auth.uid()::text = user_id);
CREATE POLICY "Users can create their own bookings" ON bookings FOR INSERT WITH CHECK (auth.uid()::text = user_id);


-- =============================================
-- FILE: 02_production_rbac_wallet_payment.sql
-- =============================================

-- Production: profiles (RBAC + FCM), wallet ledger, payment audit, booking extras
-- Apply after 01_schema.sql. Grant admin in SQL: UPDATE public.profiles SET app_role = 'admin' WHERE id = '<auth user uuid>';

-- ---------------------------------------------------------------------------
-- Profiles (1:1 with auth.users)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    full_name TEXT,
    app_role TEXT NOT NULL DEFAULT 'traveler',
    fcm_token TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT profiles_app_role_check CHECK (
        app_role IN (
            'traveler',
            'agency',
            'hotel_owner',
            'guide',
            'partner',
            'moderator',
            'admin',
            'super_admin'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_profiles_app_role ON public.profiles (app_role);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Optional self-insert if trigger did not run (e.g. legacy users)
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, app_role)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
        'traveler'
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Bookings: payment + structured extras (JSON)
-- ---------------------------------------------------------------------------
ALTER TABLE public.bookings
    ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE public.bookings
    ADD COLUMN IF NOT EXISTS extras JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_bookings_payment_status ON public.bookings (payment_status);

-- ---------------------------------------------------------------------------
-- Payment transactions (idempotency via val_id when present)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payment_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings (id) ON DELETE SET NULL,
    user_id TEXT NOT NULL,
    gateway TEXT NOT NULL DEFAULT 'sslcommerz',
    tran_id TEXT,
    val_id TEXT,
    amount NUMERIC(12, 2),
    payment_status TEXT NOT NULL,
    gateway_response JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS payment_transactions_val_id_key
    ON public.payment_transactions (val_id)
    WHERE val_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_transactions_booking_id ON public.payment_transactions (booking_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_user_id ON public.payment_transactions (user_id);

ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payment_transactions_select_own" ON public.payment_transactions;
CREATE POLICY "payment_transactions_select_own" ON public.payment_transactions
    FOR SELECT
    USING (user_id = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- Wallets + ledger (read from app; writes prefer Edge/service role)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wallets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL UNIQUE REFERENCES auth.users (id) ON DELETE CASCADE,
    current_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'BDT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.wallet_ledger (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_id UUID NOT NULL REFERENCES public.wallets (id) ON DELETE CASCADE,
    transaction_type TEXT NOT NULL,
    reference_type TEXT,
    reference_id UUID,
    debit NUMERIC(12, 2) NOT NULL DEFAULT 0,
    credit NUMERIC(12, 2) NOT NULL DEFAULT 0,
    balance_after NUMERIC(12, 2),
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wallet_ledger_wallet_id ON public.wallet_ledger (wallet_id);

ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "wallets_select_own" ON public.wallets;
CREATE POLICY "wallets_select_own" ON public.wallets FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "wallets_insert_own" ON public.wallets;
CREATE POLICY "wallets_insert_own" ON public.wallets FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "wallet_ledger_select_own" ON public.wallet_ledger;
CREATE POLICY "wallet_ledger_select_own" ON public.wallet_ledger
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.wallets w
            WHERE w.id = wallet_ledger.wallet_id AND w.user_id = auth.uid()
        )
    );


-- =============================================
-- FILE: 03_security_inventory_notifications.sql
-- =============================================

-- P1 Security + RLS | P2 Tour seat inventory (atomic) | P4 Audit | P5 Notification queue | P6 Analytics
-- Run after 02_production_rbac_wallet_payment.sql

-- ---------------------------------------------------------------------------
-- Staff helper (admin / super_admin / moderator)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.profiles p
        WHERE
            p.id = auth.uid()
            AND p.app_role IN ('admin', 'super_admin', 'moderator')
    );
$$;

-- ---------------------------------------------------------------------------
-- Tour departures: capacity + booked_seats (atomic updates via RPC only)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tour_departures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tour_id TEXT NOT NULL REFERENCES public.tours (id) ON DELETE CASCADE,
    departure_date DATE NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 30,
    booked_seats INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT tour_departures_unique_slot UNIQUE (tour_id, departure_date),
    CONSTRAINT tour_departures_capacity_chk CHECK (
        capacity > 0
        AND booked_seats >= 0
        AND booked_seats <= capacity
    )
);

CREATE INDEX IF NOT EXISTS idx_tour_departures_tour ON public.tour_departures (tour_id);

ALTER TABLE public.tour_departures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tour_departures_select_public" ON public.tour_departures;
CREATE POLICY "tour_departures_select_public" ON public.tour_departures FOR SELECT USING (true);

-- No direct INSERT/UPDATE for clients â€” only SECURITY DEFINER RPCs

-- ---------------------------------------------------------------------------
-- Atomic tour booking: reserve seats + insert booking (single transaction)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_tour_booking_atomic(
    p_user_id TEXT,
    p_tour_id TEXT,
    p_booking_date DATE,
    p_total_price NUMERIC,
    p_seats INTEGER,
    p_extras JSONB DEFAULT '{}'::jsonb
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    cap INTEGER;
    new_id UUID;
    merged JSONB;
BEGIN
    IF p_user_id IS DISTINCT FROM (auth.uid())::text THEN
        RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
    END IF;

    IF p_seats IS NULL OR p_seats < 1 OR p_seats > 99 THEN
        RAISE EXCEPTION 'invalid_seats' USING ERRCODE = '23514';
    END IF;

    SELECT COALESCE(NULLIF(group_size_max, 0), 30) INTO cap FROM public.tours WHERE id = p_tour_id;
    IF cap IS NULL THEN
        RAISE EXCEPTION 'tour_not_found' USING ERRCODE = '23503';
    END IF;

    INSERT INTO public.tour_departures (tour_id, departure_date, capacity, booked_seats)
    VALUES (p_tour_id, p_booking_date, cap, 0)
    ON CONFLICT (tour_id, departure_date) DO NOTHING;

    UPDATE public.tour_departures td
    SET booked_seats = td.booked_seats + p_seats
    WHERE
        td.tour_id = p_tour_id
        AND td.departure_date = p_booking_date
        AND td.booked_seats + p_seats <= td.capacity;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'capacity_exceeded' USING ERRCODE = '23514';
    END IF;

    merged := COALESCE(p_extras, '{}'::jsonb) || jsonb_build_object('seats', p_seats);

    INSERT INTO public.bookings (
        user_id,
        entity_id,
        entity_type,
        booking_date,
        total_price,
        status,
        payment_status,
        extras
    )
    VALUES (
        p_user_id,
        p_tour_id,
        'tour',
        p_booking_date,
        p_total_price,
        'pending',
        'pending',
        merged
    )
    RETURNING id INTO new_id;

    RETURN new_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_tour_booking_atomic (TEXT, TEXT, DATE, NUMERIC, INTEGER, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_tour_booking_atomic (TEXT, TEXT, DATE, NUMERIC, INTEGER, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_tour_booking_atomic (TEXT, TEXT, DATE, NUMERIC, INTEGER, JSONB) TO service_role;

-- ---------------------------------------------------------------------------
-- Release inventory on payment failure / cancel (Edge service_role only)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.release_booking_inventory(p_booking_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    b RECORD;
    seats INTEGER;
BEGIN
    SELECT id, entity_type, entity_id, booking_date, extras INTO b
    FROM public.bookings
    WHERE id = p_booking_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    IF b.entity_type IS DISTINCT FROM 'tour' THEN
        RETURN;
    END IF;

    seats := COALESCE((b.extras ->> 'seats')::integer, 1);
    IF seats < 1 THEN
        seats := 1;
    END IF;

    UPDATE public.tour_departures td
    SET booked_seats = GREATEST(0, td.booked_seats - seats)
    WHERE
        td.tour_id = b.entity_id
        AND td.departure_date = b.booking_date;
END;
$$;

REVOKE ALL ON FUNCTION public.release_booking_inventory (UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.release_booking_inventory (UUID) TO service_role;

-- ---------------------------------------------------------------------------
-- Audit log (writes from Edge / service_role; staff can read)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id UUID,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id UUID,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- entity_id nullable for gateway-level failures before full row load

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON public.audit_logs (created_at DESC);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_logs_staff_select" ON public.audit_logs;
CREATE POLICY "audit_logs_staff_select" ON public.audit_logs FOR SELECT USING (public.is_staff ());

-- ---------------------------------------------------------------------------
-- Notification queue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notification_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    action_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notification_queue_user ON public.notification_queue (user_id);
CREATE INDEX IF NOT EXISTS idx_notification_queue_status ON public.notification_queue (status);

ALTER TABLE public.notification_queue ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notification_queue_select_own" ON public.notification_queue;
CREATE POLICY "notification_queue_select_own" ON public.notification_queue FOR SELECT USING (user_id = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- Analytics events (client may insert own; staff may read all)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    user_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analytics_events_name_created ON public.analytics_events (name, created_at DESC);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "analytics_insert_authenticated" ON public.analytics_events;
CREATE POLICY "analytics_insert_authenticated" ON public.analytics_events FOR INSERT TO authenticated
WITH CHECK (
    user_id IS NULL
    OR user_id = auth.uid()::text
);

DROP POLICY IF EXISTS "analytics_select_own_or_staff" ON public.analytics_events;
CREATE POLICY "analytics_select_own_or_staff" ON public.analytics_events FOR SELECT USING (
    public.is_staff ()
    OR user_id = auth.uid()::text
);

-- ---------------------------------------------------------------------------
-- RLS: public catalog tables
-- ---------------------------------------------------------------------------
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "districts_select_public" ON public.districts;
CREATE POLICY "districts_select_public" ON public.districts FOR SELECT USING (true);

ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "hotels_select_public" ON public.hotels;
CREATE POLICY "hotels_select_public" ON public.hotels FOR SELECT USING (true);

ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "restaurants_select_public" ON public.restaurants;
CREATE POLICY "restaurants_select_public" ON public.restaurants FOR SELECT USING (true);

-- ---------------------------------------------------------------------------
-- Reviews: public read, own write
-- ---------------------------------------------------------------------------
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reviews_select_public" ON public.reviews;
CREATE POLICY "reviews_select_public" ON public.reviews FOR SELECT USING (true);

DROP POLICY IF EXISTS "reviews_insert_own" ON public.reviews;
CREATE POLICY "reviews_insert_own" ON public.reviews FOR INSERT TO authenticated
WITH CHECK (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "reviews_update_own" ON public.reviews;
CREATE POLICY "reviews_update_own" ON public.reviews FOR UPDATE TO authenticated USING (auth.uid()::text = user_id)
WITH CHECK (auth.uid()::text = user_id);

DROP POLICY IF EXISTS "reviews_delete_own" ON public.reviews;
CREATE POLICY "reviews_delete_own" ON public.reviews FOR DELETE TO authenticated USING (auth.uid()::text = user_id);

-- ---------------------------------------------------------------------------
-- Bookings + payment_transactions: staff read
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "bookings_select_staff" ON public.bookings;
CREATE POLICY "bookings_select_staff" ON public.bookings FOR SELECT USING (public.is_staff ());

DROP POLICY IF EXISTS "payment_transactions_select_staff" ON public.payment_transactions;
CREATE POLICY "payment_transactions_select_staff" ON public.payment_transactions FOR SELECT USING (public.is_staff ());

DROP POLICY IF EXISTS "profiles_select_staff" ON public.profiles;
CREATE POLICY "profiles_select_staff" ON public.profiles FOR SELECT USING (public.is_staff ());


-- =============================================
-- FILE: 04_production_upgrade.sql
-- =============================================

-- Production Upgrade: Additional tables and indexes for V3 architecture
-- Apply after 02_production_rbac_wallet_payment.sql and 03_security_inventory_notifications.sql

-- ---------------------------------------------------------------------------
-- Booking Items (normalized per booking)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.booking_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES public.bookings (id) ON DELETE CASCADE,
    item_type TEXT NOT NULL, -- e.g., 'tour', 'hotel', 'ticket'
    item_id TEXT NOT NULL,   -- reference to the entity (tour_id, hotel_id, etc.)
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_items_booking_id ON public.booking_items (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_items_item ON public.booking_items (item_type, item_id);

-- ---------------------------------------------------------------------------
-- Booking Travelers (normalize traveler details per booking)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.booking_travelers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID NOT NULL REFERENCES public.bookings (id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    age INTEGER,
    nid TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_booking_travelers_booking_id ON public.booking_travelers (booking_id);

-- ---------------------------------------------------------------------------
-- Tour Schedules (departure slots) - alias for tour_departures (kept for backward compat)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tour_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tour_id TEXT NOT NULL REFERENCES public.tours (id) ON DELETE CASCADE,
    departure_date DATE NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 30,
    booked_seats INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tour_schedules_tour ON public.tour_schedules (tour_id);
CREATE INDEX IF NOT EXISTS idx_tour_schedules_date ON public.tour_schedules (departure_date);

ALTER TABLE public.tour_schedules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "tour_schedules_select_public" ON public.tour_schedules;
CREATE POLICY "tour_schedules_select_public" ON public.tour_schedules FOR SELECT USING (true);

-- ---------------------------------------------------------------------------
-- Hotel Rooms and Inventory
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hotel_rooms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hotel_id TEXT NOT NULL REFERENCES public.hotels (id) ON DELETE CASCADE,
    room_type TEXT NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 2,
    price_per_night NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hotel_rooms_hotel ON public.hotel_rooms (hotel_id);

CREATE TABLE IF NOT EXISTS public.hotel_room_inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id UUID NOT NULL REFERENCES public.hotel_rooms (id) ON DELETE CASCADE,
    date DATE NOT NULL,
    available INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hotel_room_inventory_room ON public.hotel_room_inventory (room_id);
CREATE INDEX IF NOT EXISTS idx_hotel_room_inventory_date ON public.hotel_room_inventory (date);

ALTER TABLE public.hotel_rooms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "hotel_rooms_select_public" ON public.hotel_rooms;
CREATE POLICY "hotel_rooms_select_public" ON public.hotel_rooms FOR SELECT USING (true);

ALTER TABLE public.hotel_room_inventory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "hotel_room_inventory_select_public" ON public.hotel_room_inventory;
CREATE POLICY "hotel_room_inventory_select_public" ON public.hotel_room_inventory FOR SELECT USING (true);

-- ---------------------------------------------------------------------------
-- Tour Agencies
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tour_agencies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
    agency_name TEXT NOT NULL,
    verification_status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'verified', 'rejected'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.tour_agencies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tour_agencies_select_public" ON public.tour_agencies FOR SELECT USING (true);
CREATE POLICY "tour_agencies_manage_own" ON public.tour_agencies FOR ALL USING (profile_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Wishlists, Forum, and Community
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wishlists (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
    item_type TEXT NOT NULL, -- 'tour', 'hotel'
    item_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, item_type, item_id)
);

ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "wishlist_manage_own" ON public.wishlists FOR ALL USING (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.forum_threads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.forum_threads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "forum_threads_select_public" ON public.forum_threads FOR SELECT USING (true);
CREATE POLICY "forum_threads_insert_auth" ON public.forum_threads FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "forum_threads_manage_own" ON public.forum_threads FOR UPDATE USING (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.forum_replies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id UUID NOT NULL REFERENCES public.forum_threads (id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.forum_replies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "forum_replies_select_public" ON public.forum_replies FOR SELECT USING (true);
CREATE POLICY "forum_replies_insert_auth" ON public.forum_replies FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "forum_replies_manage_own" ON public.forum_replies FOR UPDATE USING (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS public.lost_found_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    item_type TEXT NOT NULL, -- 'lost', 'found'
    location TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open', -- 'open', 'resolved'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.lost_found_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "lost_found_select_public" ON public.lost_found_items FOR SELECT USING (true);
CREATE POLICY "lost_found_insert_auth" ON public.lost_found_items FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "lost_found_manage_own" ON public.lost_found_items FOR UPDATE USING (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- ALTER existing tables for production enhancements
-- ---------------------------------------------------------------------------
DO $$ 
BEGIN 
    -- Bookings enhancements
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bookings' AND column_name='booking_code') THEN
        ALTER TABLE public.bookings ADD COLUMN booking_code TEXT UNIQUE;
        ALTER TABLE public.bookings ADD COLUMN subtotal NUMERIC(12,2);
        ALTER TABLE public.bookings ADD COLUMN tax_amount NUMERIC(12,2);
        ALTER TABLE public.bookings ADD COLUMN total_amount NUMERIC(12,2);
    END IF;

    -- Tours enhancements
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tours' AND column_name='slug') THEN
        ALTER TABLE public.tours ADD COLUMN slug TEXT UNIQUE;
        ALTER TABLE public.tours ADD COLUMN agency_id UUID REFERENCES public.tour_agencies(id);
        ALTER TABLE public.tours ADD COLUMN status TEXT DEFAULT 'active';
    END IF;

    -- Hotels enhancements
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='hotels' AND column_name='slug') THEN
        ALTER TABLE public.hotels ADD COLUMN slug TEXT UNIQUE;
        ALTER TABLE public.hotels ADD COLUMN owner_id UUID REFERENCES public.profiles(id);
        ALTER TABLE public.hotels ADD COLUMN star_rating INTEGER;
    END IF;

    -- Payment transactions enhancements
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payment_transactions' AND column_name='paid_at') THEN
        ALTER TABLE public.payment_transactions ADD COLUMN paid_at TIMESTAMPTZ;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Hotel Booking Atomic RPC
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_hotel_booking_atomic(
    p_user_id UUID,
    p_hotel_id TEXT,
    p_room_id UUID,
    p_booking_date DATE,
    p_total_price NUMERIC,
    p_travelers JSONB,
    p_extras JSONB DEFAULT '{}'::jsonb
) RETURNS UUID AS $$
DECLARE
    v_booking_id UUID;
    v_traveler JSONB;
BEGIN
    -- 1. Check and decrement inventory
    UPDATE public.hotel_room_inventory
    SET available = available - 1
    WHERE room_id = p_room_id AND date = p_booking_date AND available > 0;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No inventory available for the selected date and room type.';
    END IF;

    -- 2. Create the main booking
    INSERT INTO public.bookings (
        user_id, entity_id, entity_type, booking_date, total_price, status, payment_status, extras, booking_code
    ) VALUES (
        p_user_id, p_hotel_id, 'hotel', p_booking_date, p_total_price, 'pending', 'pending', p_extras, 'HOTEL-' || upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 8))
    ) RETURNING id INTO v_booking_id;

    -- 3. Insert into booking_items
    INSERT INTO public.booking_items (booking_id, item_type, item_id, quantity, price)
    VALUES (v_booking_id, 'hotel_room', p_room_id::text, 1, p_total_price);

    -- 4. Insert travelers
    FOR v_traveler IN SELECT * FROM jsonb_array_elements(p_travelers)
    LOOP
        INSERT INTO public.booking_travelers (booking_id, full_name, age, nid)
        VALUES (v_booking_id, v_traveler->>'name', (v_traveler->>'age')::integer, v_traveler->>'nid');
    END LOOP;

    RETURN v_booking_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- End of production upgrade migration


-- =============================================
-- FILE: 05_ai_planner_persistence.sql
-- =============================================

-- Migration: AI Planner Persistence & Itineraries
-- Table to store AI-generated plans and custom user itineraries

CREATE TABLE IF NOT EXISTS public.itineraries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    destination TEXT,
    duration_days INTEGER,
    start_date DATE,
    budget_estimate NUMERIC(12,2),
    plan_data JSONB NOT NULL, -- Full itinerary details (days, activities, costs)
    is_public BOOLEAN DEFAULT FALSE,
    share_slug TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS
ALTER TABLE public.itineraries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "itineraries_select_own_or_public" 
ON public.itineraries FOR SELECT 
USING (user_id = auth.uid() OR is_public = true);

CREATE POLICY "itineraries_insert_auth" 
ON public.itineraries FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "itineraries_update_own" 
ON public.itineraries FOR UPDATE 
USING (user_id = auth.uid());

CREATE POLICY "itineraries_delete_own" 
ON public.itineraries FOR DELETE 
USING (user_id = auth.uid());

-- Indexes
CREATE INDEX IF NOT EXISTS idx_itineraries_user ON public.itineraries (user_id);
CREATE INDEX IF NOT EXISTS idx_itineraries_slug ON public.itineraries (share_slug);


-- =============================================
-- FILE: 06_community_v2_partners.sql
-- =============================================

-- Migration: Community V2 - Travel Partner Requests
-- Table to store travel partner matching requests

CREATE TABLE IF NOT EXISTS public.travel_partner_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
    destination_id TEXT NOT NULL, -- Reference to district ID
    travel_date DATE NOT NULL,
    duration TEXT, -- e.g., '3-5 days'
    budget_range TEXT,
    description TEXT NOT NULL,
    interests TEXT[], -- Array of interest tags
    status TEXT DEFAULT 'active', -- 'active', 'matched', 'expired', 'cancelled'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS
ALTER TABLE public.travel_partner_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "partners_select_public" 
ON public.travel_partner_requests FOR SELECT 
USING (status = 'active');

CREATE POLICY "partners_insert_auth" 
ON public.travel_partner_requests FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "partners_manage_own" 
ON public.travel_partner_requests FOR ALL 
USING (user_id = auth.uid());

-- Indexes
CREATE INDEX IF NOT EXISTS idx_partners_user ON public.travel_partner_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_partners_dest ON public.travel_partner_requests (destination_id);
CREATE INDEX IF NOT EXISTS idx_partners_status ON public.travel_partner_requests (status);


-- =============================================
-- FILE: 07_analytics_audit.sql
-- =============================================

-- Migration: Analytics & Audit Logs
-- System for tracking events and audit trails

CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles (id) ON DELETE SET NULL,
    event_name TEXT NOT NULL,
    event_data JSONB DEFAULT '{}',
    page_url TEXT,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_id UUID REFERENCES public.profiles (id) ON DELETE SET NULL,
    action_type TEXT NOT NULL, -- 'create', 'update', 'delete', 'login'
    entity_type TEXT NOT NULL, -- 'booking', 'tour', 'profile'
    entity_id TEXT,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Analytics: Allow authenticated users to insert events
CREATE POLICY "analytics_insert" 
ON public.analytics_events FOR INSERT 
WITH CHECK (true); -- Anyone can send analytics (IP/UA will be captured)

-- Audit: Only admins can view
CREATE POLICY "audit_view_admin" 
ON public.audit_logs FOR SELECT 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND (role = 'admin' OR role = 'super_admin')
    )
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_analytics_event ON public.analytics_events (event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_user ON public.analytics_events (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON public.audit_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON public.audit_logs (entity_type, entity_id);


-- =============================================
-- FILE: 08_admin_business_mgmt.sql
-- =============================================

-- Migration: Admin & Business Management Enhancements
-- Tools for managing partners and auditing

-- Add verification details to agencies
ALTER TABLE public.tour_agencies 
ADD COLUMN IF NOT EXISTS trade_license_id TEXT,
ADD COLUMN IF NOT EXISTS contact_person TEXT,
ADD COLUMN IF NOT EXISTS business_address TEXT;

-- Create a view for admin to see user stats (if needed)
-- But we can just use the profiles table

-- Ensure audit logs capture role changes
CREATE OR REPLACE FUNCTION public.log_role_change()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.app_role IS DISTINCT FROM NEW.app_role THEN
        INSERT INTO public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
        VALUES (
            auth.uid(),
            'update_role',
            'profile',
            NEW.id,
            jsonb_build_object('old_role', OLD.app_role, 'new_role', NEW.app_role)
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_log_role_change ON public.profiles;
CREATE TRIGGER trigger_log_role_change
AFTER UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.log_role_change();


-- =============================================
-- FILE: 09_social_gamification.sql
-- =============================================

-- Migration: Social Discovery & Gamification
-- Adds follows, achievements, and XP systems

-- 1. Extend profiles with XP and Levels
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS traveler_type TEXT DEFAULT 'explorer';

-- 2. Follows Table
CREATE TABLE IF NOT EXISTS public.follows (
    follower_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    following_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (follower_id, following_id),
    CONSTRAINT no_self_follow CHECK (follower_id <> following_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_follower ON public.follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following ON public.follows(following_id);

ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "follows_select_public" ON public.follows FOR SELECT USING (true);
CREATE POLICY "follows_insert_own" ON public.follows FOR INSERT WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "follows_delete_own" ON public.follows FOR DELETE USING (auth.uid() = follower_id);

-- 3. Achievements Catalog
CREATE TABLE IF NOT EXISTS public.achievements (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon TEXT,
    xp_reward INTEGER DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed some achievements
INSERT INTO public.achievements (id, title, description, icon, xp_reward) VALUES
('first_trip', 'First Adventure', 'Completed your first booking on Madventure', 'ðŸŽ’', 100),
('review_king', 'Review King', 'Posted 5 or more tour reviews', 'â­', 250),
('coastal_explorer', 'Coastal Explorer', 'Visited 3 beach destinations', 'ðŸ–ï¸', 500),
('social_butterfly', 'Social Butterfly', 'Participated in 10 forum discussions', 'ðŸ’¬', 200)
ON CONFLICT DO NOTHING;

-- 4. User Achievements
CREATE TABLE IF NOT EXISTS public.user_achievements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    achievement_id TEXT REFERENCES public.achievements(id) ON DELETE CASCADE,
    earned_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, achievement_id)
);

ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_achievements_select_public" ON public.user_achievements FOR SELECT USING (true);

-- 5. RPC to update XP and calculate level
CREATE OR REPLACE FUNCTION public.add_user_xp(p_user_id UUID, p_amount INTEGER)
RETURNS VOID AS $$
DECLARE
    v_new_xp INTEGER;
    v_new_level INTEGER;
BEGIN
    UPDATE public.profiles
    SET xp = xp + p_amount
    WHERE id = p_user_id
    RETURNING xp INTO v_new_xp;

    -- Simple leveling logic: level = floor(sqrt(xp / 100)) + 1
    v_new_level := floor(sqrt(v_new_xp / 100.0)) + 1;

    UPDATE public.profiles
    SET level = v_new_level
    WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =============================================
-- FILE: 10_places_districts.sql
-- =============================================

-- Migration: Districts and Places Data
-- Migrates static JS data to live SQL tables

-- 1. Districts Table
CREATE TABLE IF NOT EXISTS public.districts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL UNIQUE,
    division VARCHAR(100) NOT NULL,
    spots JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Places Table (Popular Destinations)
CREATE TABLE IF NOT EXISTS public.places (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    district_name VARCHAR(100) REFERENCES public.districts(name),
    name VARCHAR(255) NOT NULL UNIQUE,
    location VARCHAR(255),
    region VARCHAR(100),
    image TEXT,
    description TEXT,
    details TEXT,
    fare_chart JSONB DEFAULT '[]',
    hidden_spots JSONB DEFAULT '[]',
    food_hotels JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.places ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on districts" ON public.districts FOR SELECT USING (true);
CREATE POLICY "Allow public read on places" ON public.places FOR SELECT USING (true);

-- 4. Seed Districts
-- (Abbreviated for demonstration, but including major ones)
INSERT INTO public.districts (name, division, spots) VALUES
('Dhaka', 'Dhaka Division', '["Lalbagh Fort", "Ahsan Manzil", "National Parliament House"]'),
('Cox''s Bazar', 'Chittagong Division', '["Sea Beach", "Himchari", "Inani", "Saint Martin''s Island"]'),
('Sylhet', 'Sylhet Division', '["Jaflong", "Ratargul", "Bisnakandi", "Shahjalal Mazar"]'),
('Rangamati', 'Chittagong Division', '["Sajek Valley", "Kaptai Lake", "Hanging Bridge"]'),
('Bandarban', 'Chittagong Division', '["Nilgiri", "Nilachal", "Boga Lake", "Keokradong"]'),
('Khulna', 'Khulna Division', '["Sundarbans", "Rupsha Bridge"]'),
('Patuakhali', 'Barishal Division', '["Kuakata Sea Beach", "Payra Port"]'),
('Noakhali', 'Chittagong Division', '["Nijhum Dwip", "Gandhi Ashram"]'),
('Moulvibazar', 'Sylhet Division', '["Sreemangal Tea Gardens", "Lawachara National Park"]'),
('Rajshahi', 'Rajshahi Division', '["Varendra Research Museum", "Bagha Mosque"]'),
('Bogra', 'Rajshahi Division', '["Mahasthangarh", "Momo Inn"]'),
('Mymensingh', 'Mymensingh Division', '["Shashi Lodge", "Birishiri"]');

-- 5. Seed Places
INSERT INTO public.places (name, district_name, location, region, image, description, details, fare_chart, hidden_spots, food_hotels) VALUES
('Cox''s Bazar', 'Cox''s Bazar', 'Cox''s Bazar', 'Chittagong Division', 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'The world''s longest natural sea beach.', 'Cox''s Bazar is the tourist capital of Bangladesh.', '[{"vehicle": "Rickshaw", "rate": "30-50 BDT"}]', '["Mermaid Beach", "Radiant Fish World"]', '["Poushee", "Salt Bistro"]'),
('Sajek Valley', 'Rangamati', 'Rangamati', 'Chittagong Hill Tracts', 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'The Queen of Hills.', 'Located in Baghaichhari Upazila. Famous for Ruilui Para.', '[{"vehicle": "Chander Gari", "rate": "8000-10000 BDT"}]', '["Hajachora Waterfall"]', '["Runmoy Resort"]'),
('Sundarbans', 'Khulna', 'Khulna', 'Khulna Division', 'https://images.unsplash.com/photo-1544228906-8d591e528b61?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'The largest mangrove forest.', 'UNESCO World Heritage site.', '[{"vehicle": "Boat Tour", "rate": "3000-5000 BDT"}]', '["Kotka Beach", "Hiran Point"]', '["Ship Catering"]'),
('Saint Martin''s Island', 'Cox''s Bazar', 'Bay of Bengal', 'Chittagong Division', 'https://images.unsplash.com/photo-1540206351-d6465b3ac5c1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'The only coral island.', 'Known for its crystal clear blue water.', '[{"vehicle": "Van Tour", "rate": "200-300 BDT"}]', '["Chera Dwip"]', '["Blue Marine"]');


-- =============================================
-- FILE: 11_tours_data.sql
-- =============================================

-- Migration: Tours and Schedules
-- Migrates mock tours to live SQL tables

-- 1. Tours Table
CREATE TABLE IF NOT EXISTS public.tours (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    destination VARCHAR(100),
    price NUMERIC(12,2) NOT NULL,
    duration VARCHAR(50),
    category VARCHAR(50), -- e.g. 'backpack', 'luxury', 'student'
    images TEXT[] DEFAULT '{}',
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.tours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on tours" ON public.tours FOR SELECT USING (true);

-- 3. Seed Tours (Student Backpack Trips under 2000 BDT)
INSERT INTO public.tours (title, description, destination, price, duration, category, is_featured, images) VALUES
('Sajek Valley Weekend', 'Experience the clouds at Sajek Valley.', 'Rangamati', 1950, '2 Days 1 Night', 'student', true, '{"https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff"}'),
('Sylhet Tea Trail', 'Visit Jaflong and Ratargul Swamp Forest.', 'Sylhet', 1800, '3 Days 2 Nights', 'student', true, '{"https://images.unsplash.com/photo-1598556776374-2c358606f287"}'),
('Sundarbans Day Trip', 'Karamjal and Harbaria mangrove exploration.', 'Khulna', 1500, '1 Day', 'student', true, '{"https://images.unsplash.com/photo-1544228906-8d591e528b61"}'),
('Saint Martin Beach Camp', 'Camping at the coral island.', 'Cox''s Bazar', 2000, '2 Days 1 Night', 'student', true, '{"https://images.unsplash.com/photo-1540206351-d6465b3ac5c1"}');


-- =============================================
-- FILE: 12_emergency_data.sql
-- =============================================

-- Migration: Emergency Services
-- Migrates mock emergency data to live SQL tables

-- 1. Emergency Services Table
CREATE TABLE IF NOT EXISTS public.emergency_services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    district_id UUID REFERENCES districts(id),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50), -- 'mechanic', 'pharmacy', 'hospital', 'police'
    address TEXT,
    phone VARCHAR(50),
    whatsapp VARCHAR(50),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    is_open_24h BOOLEAN DEFAULT FALSE,
    specialities TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.emergency_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on emergency_services" ON public.emergency_services FOR SELECT USING (true);

-- 3. Seed some data (Generic for now, focusing on Cox's Bazar as example)
-- We need to find a district ID first, but for the seed we can just insert and let user add more.
-- Actually, I'll insert some sample ones.
INSERT INTO public.emergency_services (name, type, address, phone, is_open_24h, specialities) VALUES
('Cox''s Bazar General Hospital', 'hospital', 'Hospital Road, Cox''s Bazar', '01711-000000', true, '{"ICU", "Emergency", "Surgery"}'),
('Tourist Police Cox''s Bazar', 'police', 'Beach Point, Cox''s Bazar', '01711-111111', true, '{"Security", "Assistance"}'),
('City Pharmacy', 'pharmacy', 'Main Road, Cox''s Bazar', '01711-222222', true, '{"Medicine", "First Aid"}'),
('Bike Care Point', 'mechanic', 'Kolatoli, Cox''s Bazar', '01711-333333', false, '{"Engine", "Tyre", "Bike"}');


-- =============================================
-- FILE: 13_unicorn_phase1.sql
-- =============================================

-- Migration: Unicorn Upgrade Phase 1 (Foundation)
-- Implements Media Management, Inventory Locking, Refunds, and Reviews

-- 1. Media Management System
CREATE TABLE IF NOT EXISTS public.media_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_type VARCHAR(50), -- 'district', 'place', 'tour', 'user'
    owner_id UUID,
    file_type VARCHAR(30), -- 'image', 'video', 'doc'
    file_url TEXT NOT NULL,
    mime_type VARCHAR(100),
    file_size BIGINT,
    storage_provider VARCHAR(50) DEFAULT 'supabase',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Inventory Locking (Prevent Overbooking)
CREATE TABLE IF NOT EXISTS public.booking_locks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    schedule_id UUID,
    locked_seats INTEGER NOT NULL DEFAULT 1,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Refund System
CREATE TABLE IF NOT EXISTS public.refund_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings(id),
    reason TEXT NOT NULL,
    refund_amount NUMERIC(12,2) NOT NULL,
    refund_status VARCHAR(30) DEFAULT 'pending', -- 'pending', 'approved', 'rejected', 'processed'
    admin_notes TEXT,
    requested_at TIMESTAMPTZ DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

-- 4. Review System (Production Grade)
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    entity_type VARCHAR(30), -- 'tour', 'hotel', 'place'
    entity_id UUID,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    review TEXT,
    verified_booking BOOLEAN DEFAULT FALSE,
    is_published BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Search Optimization (Full-Text Search)
-- Adding tsvector column to places for fast search
ALTER TABLE public.places ADD COLUMN IF NOT EXISTS search_vector tsvector;
CREATE INDEX IF NOT EXISTS places_search_idx ON public.places USING GIN(search_vector);

-- Function to update search vector
CREATE OR REPLACE FUNCTION places_search_trigger() RETURNS trigger AS $$
BEGIN
  new.search_vector :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.description, '')), 'B');
  return new;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_places_search_update
BEFORE INSERT OR UPDATE ON public.places
FOR EACH ROW EXECUTE FUNCTION places_search_trigger();

-- 6. Enable RLS for new tables
ALTER TABLE public.media_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refund_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read on media_files" ON public.media_files FOR SELECT USING (true);
CREATE POLICY "Allow public read on reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Users can view own locks" ON public.booking_locks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can view own refunds" ON public.refund_requests FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.bookings b WHERE b.id = booking_id AND b.user_id = auth.uid())
);


-- =============================================
-- FILE: 14_unicorn_phase2.sql
-- =============================================

-- Migration: Unicorn Upgrade Phase 2 (Business Engines)
-- Implements Coupons, Multi-Currency, and Tax Rules

-- 1. Coupon & Promo Engine
CREATE TABLE IF NOT EXISTS public.coupons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    discount_type VARCHAR(20) NOT NULL, -- 'percentage', 'fixed'
    discount_value NUMERIC(12,2) NOT NULL,
    min_purchase NUMERIC(12,2) DEFAULT 0,
    max_discount NUMERIC(12,2),
    expiry_date TIMESTAMPTZ,
    usage_limit INTEGER,
    usage_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.coupon_usages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coupon_id UUID REFERENCES public.coupons(id),
    user_id UUID REFERENCES auth.users(id),
    booking_id UUID REFERENCES public.bookings(id),
    used_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Multi-Currency Support
CREATE TABLE IF NOT EXISTS public.currencies (
    code VARCHAR(10) PRIMARY KEY, -- 'BDT', 'USD', 'EUR'
    name VARCHAR(50),
    symbol VARCHAR(10),
    exchange_rate_to_bdt NUMERIC(12,4) DEFAULT 1.0,
    is_active BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tax Engine
CREATE TABLE IF NOT EXISTS public.tax_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL, -- 'VAT', 'Tourism Tax'
    percentage NUMERIC(5,2) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Notification Preferences
CREATE TABLE IF NOT EXISTS public.notification_preferences (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id),
    email_enabled BOOLEAN DEFAULT TRUE,
    push_enabled BOOLEAN DEFAULT TRUE,
    sms_enabled BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. RLS
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.currencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on active coupons" ON public.coupons FOR SELECT USING (is_active = true);
CREATE POLICY "Allow public read on currencies" ON public.currencies FOR SELECT USING (is_active = true);
CREATE POLICY "Users can manage own preferences" ON public.notification_preferences 
    FOR ALL USING (auth.uid() = user_id);


-- =============================================
-- FILE: 15_unicorn_phase3.sql
-- =============================================

-- Migration: Unicorn Upgrade Phase 3 (Communication & CMS)
-- Implements Chat Rooms, Messages, and CMS System

-- 1. Chat System
CREATE TABLE IF NOT EXISTS public.chat_rooms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255),
    type VARCHAR(30) DEFAULT 'direct', -- 'direct', 'group', 'support'
    entity_type VARCHAR(50), -- 'tour', 'booking'
    entity_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chat_participants (
    room_id UUID REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role VARCHAR(30) DEFAULT 'member',
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id UUID REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES auth.users(id),
    message TEXT,
    message_type VARCHAR(20) DEFAULT 'text', -- 'text', 'image', 'system'
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CMS System
CREATE TABLE IF NOT EXISTS public.cms_pages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    content JSONB NOT NULL, -- Flexible content structure
    seo_metadata JSONB DEFAULT '{}',
    is_published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cms_banners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255),
    image_url TEXT NOT NULL,
    link_url TEXT,
    placement VARCHAR(50), -- 'home_hero', 'tour_listing'
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RLS
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_banners ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Participants can view their rooms" ON public.chat_rooms
    FOR SELECT USING (EXISTS (SELECT 1 FROM public.chat_participants WHERE room_id = id AND user_id = auth.uid()));

CREATE POLICY "Participants can view messages" ON public.chat_messages
    FOR SELECT USING (EXISTS (SELECT 1 FROM public.chat_participants WHERE room_id = chat_messages.room_id AND user_id = auth.uid()));

CREATE POLICY "Participants can send messages" ON public.chat_messages
    FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.chat_participants WHERE room_id = chat_messages.room_id AND user_id = auth.uid()));

CREATE POLICY "Allow public read on published CMS" ON public.cms_pages FOR SELECT USING (is_published = true);
CREATE POLICY "Allow public read on active banners" ON public.cms_banners FOR SELECT USING (is_active = true);


-- =============================================
-- FILE: 16_unicorn_phase4.sql
-- =============================================

-- Migration: Unicorn Upgrade Phase 4 (BI & Infrastructure)
-- Implements BI Aggregates and Feature Flags

-- 1. BI & Analytics Aggregates (For Dashboard Charts)
CREATE TABLE IF NOT EXISTS public.bi_daily_revenue (
    date DATE PRIMARY KEY,
    total_revenue NUMERIC(12,2) DEFAULT 0,
    booking_count INTEGER DEFAULT 0,
    commission_earned NUMERIC(12,2) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bi_user_segments (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id),
    total_spent NUMERIC(12,2) DEFAULT 0,
    booking_frequency INTEGER DEFAULT 0,
    last_booking_date DATE,
    customer_lifetime_value NUMERIC(12,2) DEFAULT 0,
    segment VARCHAR(50), -- 'VIP', 'Regular', 'Churn-Risk'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Feature Flags System
CREATE TABLE IF NOT EXISTS public.feature_flags (
    key VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255),
    is_enabled BOOLEAN DEFAULT FALSE,
    rollout_percentage INTEGER DEFAULT 100, -- 0 to 100
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RLS
ALTER TABLE public.bi_daily_revenue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bi_user_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_flags ENABLE ROW LEVEL SECURITY;

-- Analytics and Flags are mostly for Admin/System
CREATE POLICY "Allow public read on feature flags" ON public.feature_flags FOR SELECT USING (true);


-- =============================================
-- FILE: 17_postgis_geo.sql
-- =============================================

-- Migration: PostGIS & Geo-Spatial Intelligence
-- Enables PostGIS extension and implements radius search logic

-- 1. Enable PostGIS Extension
-- NOTE: This requires superuser or specific permissions on Supabase
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Add Geography Column to Places and Hotels
ALTER TABLE public.places ADD COLUMN IF NOT EXISTS location_point geography(POINT, 4326);
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS location_point geography(POINT, 4326);

-- 3. Update existing data to populate location_point
-- (Assuming latitude and longitude columns exist from previous migrations)
UPDATE public.places 
SET location_point = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

UPDATE public.hotels 
SET location_point = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

-- 4. Create Spatial Index for high-performance geo-queries
CREATE INDEX IF NOT EXISTS places_geo_idx ON public.places USING GIST(location_point);
CREATE INDEX IF NOT EXISTS hotels_geo_idx ON public.hotels USING GIST(location_point);

-- 5. Function: Find Nearby Places/Hotels
-- Usage: SELECT * FROM find_nearby_places(90.4125, 23.8103, 5000); -- 5km radius
CREATE OR REPLACE FUNCTION find_nearby_places(
    lon float, 
    lat float, 
    radius_meters float
)
RETURNS SETOF public.places AS $$
BEGIN
    RETURN QUERY
    SELECT *
    FROM public.places
    WHERE ST_DWithin(
        location_point,
        ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography,
        radius_meters
    )
    ORDER BY ST_Distance(
        location_point,
        ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography
    );
END;
$$ LANGUAGE plpgsql;


-- =============================================
-- FILE: 18_bi_intelligence_engine.sql
-- =============================================

-- Migration: Unicorn BI Intelligence Engine
-- Implements complex business logic for CLV, Churn, and Retention

-- 1. Function: Calculate Customer Lifetime Value (CLV)
-- Logic: Total revenue from user / number of months since first booking
CREATE OR REPLACE FUNCTION calculate_user_clv(target_user_id UUID)
RETURNS NUMERIC AS $$
DECLARE
    total_spent NUMERIC;
    months_active INTEGER;
BEGIN
    SELECT SUM(total_price) INTO total_spent FROM public.bookings WHERE user_id = target_user_id AND status = 'confirmed';
    SELECT GREATEST(1, EXTRACT(MONTH FROM AGE(NOW(), MIN(created_at)))::INTEGER) INTO months_active FROM public.bookings WHERE user_id = target_user_id;
    
    RETURN COALESCE(total_spent, 0); -- For now, we return total spent as lifetime value
END;
$$ LANGUAGE plpgsql;

-- 2. Function: Get Business Growth Metrics (Monthly)
CREATE OR REPLACE FUNCTION get_business_growth_metrics()
RETURNS TABLE (
    month TEXT,
    revenue NUMERIC,
    bookings_count BIGINT,
    new_users_count BIGINT,
    churn_rate NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    WITH monthly_data AS (
        SELECT 
            TO_CHAR(created_at, 'YYYY-Mon') as m,
            SUM(total_price) as rev,
            COUNT(id) as b_count,
            (SELECT COUNT(id) FROM auth.users WHERE created_at BETWEEN MIN(b.created_at) AND MAX(b.created_at)) as u_count
        FROM public.bookings b
        WHERE status = 'confirmed'
        GROUP BY TO_CHAR(created_at, 'YYYY-Mon')
        ORDER BY MIN(created_at) DESC
        LIMIT 6
    )
    SELECT 
        m, 
        COALESCE(rev, 0), 
        b_count, 
        u_count,
        15.5 -- Mock Churn Rate for now (Calculated as users who didn't book in 30 days)
    FROM monthly_data;
END;
$$ LANGUAGE plpgsql;

-- 3. Procedure: Refresh BI Aggregates
-- This can be called by a cron job or edge function
CREATE OR REPLACE FUNCTION refresh_bi_segments()
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.bi_user_segments (user_id, total_spent, booking_frequency, last_booking_date, customer_lifetime_value, segment, updated_at)
    SELECT 
        user_id,
        SUM(total_price) as total_spent,
        COUNT(id) as freq,
        MAX(created_at)::DATE as last_date,
        SUM(total_price) as clv,
        CASE 
            WHEN SUM(total_price) > 50000 THEN 'VIP'
            WHEN COUNT(id) > 5 THEN 'Regular'
            WHEN MAX(created_at) < NOW() - INTERVAL '3 months' THEN 'Churn-Risk'
            ELSE 'New'
        END as segment,
        NOW()
    FROM public.bookings
    WHERE status = 'confirmed'
    GROUP BY user_id
    ON CONFLICT (user_id) DO UPDATE SET
        total_spent = EXCLUDED.total_spent,
        booking_frequency = EXCLUDED.booking_frequency,
        last_booking_date = EXCLUDED.last_booking_date,
        customer_lifetime_value = EXCLUDED.customer_lifetime_value,
        segment = EXCLUDED.segment,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql;


-- =============================================
-- FILE: 19_unified_business_schema.sql
-- =============================================

-- Migration: Unified Business & Listing Schema
-- Supports Hotels, Restaurants, Guides, and Shops under a unified entity model.

-- 1. Businesses Table
CREATE TABLE IF NOT EXISTS public.businesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    category TEXT NOT NULL, -- 'HOTEL', 'RESTAURANT', 'TRANSPORT', 'GUIDE', 'SHOP'
    location TEXT,
    district TEXT,
    division TEXT,
    lat NUMERIC,
    lng NUMERIC,
    phone TEXT,
    whatsapp TEXT,
    facebook TEXT,
    website TEXT,
    images TEXT[],
    cover_image TEXT,
    price_range TEXT,
    amenities TEXT[],
    opening_hours TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    is_approved BOOLEAN DEFAULT FALSE,
    rating NUMERIC DEFAULT 0.0,
    review_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    booking_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_businesses_category ON public.businesses (category);
CREATE INDEX IF NOT EXISTS idx_businesses_district ON public.businesses (district);

-- 2. Listings Table (Sub-items of a business like Rooms or Tours)
CREATE TABLE IF NOT EXISTS public.listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    business_id UUID REFERENCES public.businesses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    price_unit TEXT, -- 'per_night', 'per_person', etc.
    availability BOOLEAN DEFAULT TRUE,
    max_guests INTEGER,
    images TEXT[],
    features TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. RLS Policies
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on approved businesses" ON public.businesses
    FOR SELECT USING (is_approved = true);

CREATE POLICY "Allow owners to manage their businesses" ON public.businesses
    FOR ALL USING (auth.uid() = owner_id);

CREATE POLICY "Allow public select on listings" ON public.listings
    FOR SELECT USING (true);

CREATE POLICY "Allow business owners to manage listings" ON public.listings
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.businesses
            WHERE id = listings.business_id AND owner_id = auth.uid()
        )
    );


-- =============================================
-- FILE: 20_step2_features.sql
-- =============================================

-- Migration: Step 2 Features (Transport, Cancellation, Reviews refinement)

-- 1. Transport Support
CREATE TABLE IF NOT EXISTS public.transports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_name TEXT NOT NULL,
    transport_type TEXT NOT NULL, -- 'BUS', 'LAUNCH', 'TRAIN'
    route_from TEXT NOT NULL,
    route_to TEXT NOT NULL,
    departure_time TIME NOT NULL,
    arrival_time TIME,
    price NUMERIC(12,2) NOT NULL,
    total_seats INTEGER NOT NULL,
    available_seats INTEGER NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.transports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on active transports" ON public.transports FOR SELECT USING (status = 'active');

-- 2. Cancellation Policy Engine
-- Policy types: 'FLX' (Flexible), 'MOD' (Moderate), 'STRICT' (Strict)
CREATE TABLE IF NOT EXISTS public.cancellation_policies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    refund_percentage INTEGER NOT NULL, -- percentage of refund
    deadline_days INTEGER NOT NULL, -- days before start date for this refund %
    is_default BOOLEAN DEFAULT FALSE
);

-- Add policy references to tours and hotels
ALTER TABLE public.tours ADD COLUMN IF NOT EXISTS cancellation_policy_id UUID REFERENCES public.cancellation_policies(id);
ALTER TABLE public.businesses ADD COLUMN IF NOT EXISTS cancellation_policy_id UUID REFERENCES public.cancellation_policies(id);

-- 3. Review Refinement: Ensure mandatory verified reviews
-- (Table already exists, adding trigger to check booking status if needed)
CREATE OR REPLACE FUNCTION public.check_verified_review()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.verified_booking = TRUE THEN
        IF NOT EXISTS (
            SELECT 1 FROM public.bookings 
            WHERE user_id = NEW.user_id 
            AND entity_id = NEW.entity_id 
            AND status = 'confirmed'
        ) THEN
            RAISE EXCEPTION 'Review must be linked to a confirmed booking.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Initial Cancellation Data
INSERT INTO public.cancellation_policies (name, description, refund_percentage, deadline_days, is_default)
VALUES 
('Flexible', 'Full refund 3 days before', 100, 3, true),
('Moderate', '50% refund 7 days before', 50, 7, false),
('Non-refundable', 'No refund after booking', 0, 0, false)
ON CONFLICT DO NOTHING;


-- =============================================
-- FILE: 21_step2_data.sql
-- =============================================

-- Seed data for Step 2 features

-- 1. Cancellation Policies
INSERT INTO public.cancellation_policies (name, description, refund_percentage, deadline_days, is_default)
VALUES 
('Flexible', '100% refund up to 72 hours before departure.', 100, 3, true),
('Moderate', '50% refund up to 7 days before departure.', 50, 7, false),
('Strict', 'Non-refundable.', 0, 0, false)
ON CONFLICT DO NOTHING;

-- 2. Coupons
INSERT INTO public.coupons (code, description, discount_type, discount_value, min_purchase, expiry_date, usage_limit)
VALUES 
('SAVE10', '10% discount on all tours', 'percentage', 10, 1000, '2026-12-31 23:59:59', 1000),
('WELCOME500', 'Fixed à§³500 discount for new users', 'fixed', 500, 5000, '2026-12-31 23:59:59', 500),
('EID2025', 'Special Eid discount 15%', 'percentage', 15, 2000, '2025-06-30 23:59:59', 2000)
ON CONFLICT (code) DO NOTHING;

-- 3. Transports (Initial set for searching)
INSERT INTO public.transports (provider_name, transport_type, route_from, route_to, departure_time, price, total_seats, available_seats)
VALUES 
('Hanif Enterprise', 'BUS', 'Dhaka', 'Chittagong', '22:00:00', 1200, 40, 40),
('Ena Transport', 'BUS', 'Dhaka', 'Sylhet', '08:30:00', 800, 36, 36),
('Green Line', 'BUS', 'Dhaka', 'Cox''s Bazar', '23:00:00', 2500, 30, 30),
('Parabat Express', 'TRAIN', 'Dhaka', 'Sylhet', '06:40:00', 650, 500, 500),
('Green Line Waterways', 'LAUNCH', 'Dhaka', 'Barishal', '21:00:00', 1500, 200, 200)
ON CONFLICT DO NOTHING;


-- =============================================
-- FILE: 22_sos_logs.sql
-- =============================================

-- Migration: Emergency SOS Integration

CREATE TABLE IF NOT EXISTS public.emergency_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    full_name TEXT,
    phone TEXT,
    location_lat NUMERIC,
    location_lng NUMERIC,
    status TEXT DEFAULT 'pending', -- 'pending', 'responding', 'resolved'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.emergency_logs ENABLE ROW LEVEL SECURITY;

-- Admins can see all logs, users can see only theirs (though SOS is usually one-way)
CREATE POLICY "Admins can view all emergency logs" ON public.emergency_logs 
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND app_role IN ('admin', 'super_admin'))
    );

CREATE POLICY "Users can insert emergency logs" ON public.emergency_logs 
    FOR INSERT WITH CHECK (true); -- Allow anyone to trigger SOS if authenticated


-- =============================================
-- FILE: 23_production_hardening.sql
-- =============================================

-- Final Production Hardening Migration
-- 1. Enable RLS on all relevant tables
ALTER TABLE IF EXISTS public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coupon_usages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.transports ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cancellation_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.refund_requests ENABLE ROW LEVEL SECURITY;

-- 2. Define Policies

-- Coupons: Everyone can view active coupons (for validation), but only admins can modify
DROP POLICY IF EXISTS "Public can view active coupons" ON public.coupons;
CREATE POLICY "Public can view active coupons" ON public.coupons
    FOR SELECT USING (expiry_date > NOW() AND status = 'active');

-- Transports: Everyone can view available transports
DROP POLICY IF EXISTS "Public can view active transports" ON public.transports;
CREATE POLICY "Public can view active transports" ON public.transports
    FOR SELECT USING (status = 'active');

-- Refund Requests: Users see their own, admins see all
DROP POLICY IF EXISTS "Users can view own refunds" ON public.refund_requests;
CREATE POLICY "Users can view own refunds" ON public.refund_requests
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.bookings b 
            WHERE b.id = public.refund_requests.booking_id 
            AND b.user_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Admins can view all refunds" ON public.refund_requests;
CREATE POLICY "Admins can view all refunds" ON public.refund_requests
    FOR ALL USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.app_role IN ('admin', 'super_admin'))
    );

-- 3. Inventory Protection Trigger (Prevent overbooking)
CREATE OR REPLACE FUNCTION public.check_transport_availability()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT available_seats FROM public.transports WHERE id = NEW.transport_id) < NEW.seat_count THEN
        RAISE EXCEPTION 'No more seats available on this transport.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Audit Log Table (Optional but recommended for Production)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    action TEXT,
    table_name TEXT,
    record_id TEXT,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =============================================
-- FILE: 24_gamification_badges.sql
-- =============================================

-- Gamification & Badges Integration

CREATE TABLE IF NOT EXISTS public.badges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    icon_name TEXT, -- Lucide icon name or image URL
    criteria_type TEXT, -- 'post_count', 'booking_count', 'review_count'
    criteria_value INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_badges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    badge_id UUID REFERENCES public.badges(id),
    awarded_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, badge_id)
);

-- Seed Initial Badges
INSERT INTO public.badges (name, description, icon_name, criteria_type, criteria_value)
VALUES 
('Early Explorer', 'Joined the Madventure community early.', 'Compass', 'manual', 0),
('Frequent Flyer', 'Completed 5 or more bookings.', 'Plane', 'booking_count', 5),
('Safety Guardian', 'Helped others by reporting or contributing safety tips.', 'Shield', 'manual', 0),
('Top Reviewer', 'Contributed 10 or more verified reviews.', 'Star', 'review_count', 10);

-- Policies
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view badges" ON public.badges FOR SELECT USING (true);
CREATE POLICY "Users can view own badges" ON public.user_badges FOR SELECT USING (auth.uid() = user_id);


-- =============================================
-- FILE: 25_notifications.sql
-- =============================================

-- Notification Logs for WhatsApp and SMS tracking

CREATE TABLE IF NOT EXISTS public.notification_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings(id),
    recipient_phone TEXT NOT NULL,
    notification_type TEXT NOT NULL, -- 'whatsapp', 'sms'
    message_content TEXT,
    status TEXT DEFAULT 'sent', -- 'sent', 'failed', 'delivered'
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    provider TEXT -- 'ssl_wireless', 'twilio', 'simulation'
);

-- RLS
ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view all notifications" ON public.notification_logs
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.app_role IN ('admin', 'super_admin'))
    );


-- =============================================
-- FILE: 26_blog_posts.sql
-- =============================================

-- Migration: Madventure Blog System

CREATE TABLE IF NOT EXISTS public.blog_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    cover_image TEXT,
    excerpt TEXT,
    content TEXT,
    category VARCHAR(100),
    tags TEXT[],
    author_id UUID REFERENCES public.profiles(id),
    status VARCHAR(20) DEFAULT 'draft', -- 'draft', 'published'
    language VARCHAR(10) DEFAULT 'bn', -- 'bn', 'en'
    views INTEGER DEFAULT 0,
    reading_time INTEGER,
    meta_title VARCHAR(255),
    meta_description TEXT,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_blog_status_lang ON public.blog_posts(status, language);
CREATE INDEX IF NOT EXISTS idx_blog_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_category ON public.blog_posts(category);

-- RLS Policies
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- 1. Anyone can view published posts
CREATE POLICY "Public can read published posts"
    ON public.blog_posts
    FOR SELECT
    USING (status = 'published');

-- 2. Admins can do everything
CREATE POLICY "Admins can manage all posts"
    ON public.blog_posts
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles p 
            WHERE p.id = auth.uid() AND p.app_role IN ('admin', 'super_admin')
        )
    );


-- =============================================
-- FILE: 27_youtube_embed.sql
-- =============================================

-- Add youtube_url column to relevant tables for video embedding

ALTER TABLE public.tours ADD COLUMN IF NOT EXISTS youtube_url TEXT;
ALTER TABLE public.places ADD COLUMN IF NOT EXISTS youtube_url TEXT;
ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS youtube_url TEXT;


