import React, { useState } from 'react';
import { AlertTriangle, ExternalLink, Play } from 'lucide-react';
import { PROVIDER_LABEL } from '../services/videoProviderService';

export default function VideoPlayer({ post }) {
    const [playing, setPlaying] = useState(false);
    if (!post?.embed_url) return <div className="flex aspect-video flex-col items-center justify-center gap-3 rounded-2xl bg-gradient-to-br from-slate-800 to-emerald-950 p-5 text-center text-white"><span className="text-xs font-bold">{PROVIDER_LABEL[post?.provider] || 'Video'}</span><p className="text-sm text-white/80">This platform does not provide a public inline player.</p>{post?.source_url && <a href={post.source_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold hover:bg-emerald-700"><ExternalLink size={15} /> Watch on platform</a>}<p className="flex items-center gap-1 text-[11px] text-white/50"><AlertTriangle size={12} /> Region restrictions may apply.</p></div>;
    if (playing) return <div className="relative aspect-video overflow-hidden rounded-2xl bg-black"><iframe title={post.title || 'Community video'} src={`${post.embed_url}${post.provider === 'YOUTUBE' ? '&autoplay=1' : ''}`} className="absolute inset-0 h-full w-full border-0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>;
    return <button type="button" onClick={() => setPlaying(true)} className="group relative block aspect-video w-full overflow-hidden rounded-2xl bg-slate-900 text-left"><img src={post.thumbnail_url || ''} alt="" className={`h-full w-full object-cover ${post.thumbnail_url ? '' : 'hidden'}`} /><div className="absolute inset-0 bg-gradient-to-br from-emerald-900/80 to-slate-900/80" /><span className="absolute inset-0 grid place-items-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-emerald-600 text-white shadow-xl transition group-hover:scale-110"><Play size={24} fill="currentColor" /></span></span><span className="absolute left-3 top-3 rounded-lg bg-black/60 px-2 py-1 text-xs font-bold text-white">{PROVIDER_LABEL[post.provider] || 'Video'}</span></button>;
}