const fs = require('fs');
const path = require('path');

const migrationsDir = path.join(__dirname, '..', 'supabase', 'migrations');
const outputFile = path.join(__dirname, '..', 'supabase_full_setup.sql');

try {
    const files = fs.readdirSync(migrationsDir)
        .filter(file => file.endsWith('.sql'))
        .sort(); // Sorts them alphabetically so 01_, 02_, etc. are in order

    console.log(`Found ${files.length} SQL migration files:`);
    files.forEach(f => console.log(` - ${f}`));

    let consolidatedSql = `-- =============================================\n`;
    consolidatedSql += `-- MADVENTURE - COMPLETE CONSOLIDATED MIGRATIONS\n`;
    consolidatedSql += `-- Compiled at: ${new Date().toISOString()}\n`;
    consolidatedSql += `-- Do not edit this file directly. Edit the migration scripts under supabase/migrations/ instead.\n`;
    consolidatedSql += `-- =============================================\n\n`;

    for (const file of files) {
        const filePath = path.join(migrationsDir, file);
        const content = fs.readFileSync(filePath, 'utf-8');
        consolidatedSql += `-- =============================================\n`;
        consolidatedSql += `-- FILE: ${file}\n`;
        consolidatedSql += `-- =============================================\n\n`;
        consolidatedSql += content;
        consolidatedSql += `\n\n`;
    }

    fs.writeFileSync(outputFile, consolidatedSql, 'utf-8');
    console.log(`Successfully compiled migrations to: ${outputFile}`);
} catch (err) {
    console.error('Error compiling migrations:', err);
}
