$migrationsDir = Join-Path $PSScriptRoot "..\supabase\migrations"
$outputFile = Join-Path $PSScriptRoot "..\supabase_full_setup.sql"

Write-Host "Compiling migrations from $migrationsDir to $outputFile..."

if (-not (Test-Path $migrationsDir)) {
    Write-Error "Migrations directory not found!"
    exit 1
}

$sqlFiles = Get-ChildItem -Path (Join-Path $migrationsDir "*.sql") | Sort-Object Name
Write-Host "Found $($sqlFiles.Count) SQL files."

$consolidatedSql = "-- =============================================`n"
$consolidatedSql += "-- MADVENTURE - COMPLETE CONSOLIDATED MIGRATIONS`n"
$consolidatedSql += "-- Compiled at: $((Get-Date).ToString('yyyy-MM-ddTHH:mm:ssZ'))`n"
$consolidatedSql += "-- Compiled via PowerShell`n"
$consolidatedSql += "-- Do not edit this file directly. Edit the migration scripts under supabase/migrations/ instead.`n"
$consolidatedSql += "-- =============================================`n`n"

foreach ($file in $sqlFiles) {
    Write-Host "Processing $($file.Name)..."
    $content = Get-Content $file.FullName -Raw
    $consolidatedSql += "-- =============================================`n"
    $consolidatedSql += "-- FILE: $($file.Name)`n"
    $consolidatedSql += "-- =============================================`n`n"
    $consolidatedSql += $content
    $consolidatedSql += "`n`n"
}

[System.IO.File]::WriteAllText($outputFile, $consolidatedSql, [System.Text.Encoding]::UTF8)
Write-Host "Successfully compiled migrations to $outputFile"
